### ISSUE TITLE
On Star Charts: don't need to repeat the prefix ("TOML") for each sublevel

### ISSUE THREAD

**Issue by zachmccormick** [build3/LSOA#201]

**Comment by cbradyatinquire** [comment]
This works great for most constructs on Star Chart 1 (in production).  
It does not work for ToMAngle in Star Chart 1, and it does not work for the other Star Charts (again, in production).

**Comment by zachmccormick** [comment]
Fixed it for ToMAngle in Star Chart 1. There just needed to be a space between the angle symbol and the number (it just splits on the first space).

**Comment by zachmccormick** [comment]
For posterity: I just changed those values in the database so they were all consistent

**Comment by cbradyatinquire** [comment]
Looks good!
